# config file for tp-fancontrol

#
# The temparature shift will shift the trip points for different fan speeds.
#
# A positive value means that the trip-point is at a higher temperature and
# thus the fan is less noisy. A negative shift lets the fan start earlier.
# The default value is 0.
#
#TEMP_SHIFT=10

#
# True if logging to syslog should be enabled. If zero no logging to syslog
# is enabled. All output will appear on console. This option implies QUIET=1.
# The default value is 1.
#
#LOG_SYSLOG=0

#
# If no logging to syslog is on, the output will be verbose. To be less
# verbose set QUIET to 1. The default value is 1.
#
#QUIET=1

#
# The file to store the pid of the currently running fan-control daemon in.
# The default value is /var/run/tp-fancontrol.pid
#
#PIDFILE=/var/run/tp-fancontrol.pid
